### PR TITLE
Support custom renderers and mustache templates

### PR DESCRIPTION
**Pull request by zostay**
I don't know anything about Dancer or the plans for Bailador, but this seemed like the obvious solution to supporting Mustache templates, which I'm playing with right now.

### CODE REVIEW

**Comment by zostay** [comment]
Added two more commits to fix problems with the repo and Travis CI failures.

**Comment by tadzik** [comment]
Awesome, thanks! Although while travis is fixed, it still needs the Template::Mustache dependency specified in META.info, could you add that?

**Comment by zostay** [comment]
Added the missing dependency.

**Comment by tadzik** [comment]
Thanks a lot!

**Pull request merged**
